# Minecraft / Forge
minecraft_version=1.20.1
forge_version=47.3.0

# Mod metadata
mod_version=1.0.0
mod_group_id=com.lindedaoqwq.linclient
mod_id=linclient
mod_archives_base_name=LinClient
mod_name=LinClient
mod_license=MIT
mod_authors=lindedaoqwq
mod_description=A practical, open-source, non-cheating Minecraft client mod: HUD info display, performance & visual toggles, fully configurable.

org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=false
