buildscript {
    repositories {
        maven { url = "https://maven.minecraftforge.net" }
        maven { url = "https://bmclapi2.bangbang93.com/maven" }
        maven { url = "https://repo.maven.apache.org/maven2" }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT"
    }
}

apply plugin: "net.minecraftforge.gradle.forge"

version = "1.0.0"
group = "com.lindedaoqwq"
archivesBaseName = "LinClient-1.8.9"

sourceCompatibility = targetCompatibility = "1.8"

minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "run"
    mappings = "stable_22"
}

repositories {
    maven { url = "https://repo.maven.apache.org/maven2" }
    maven { url = "https://bmclapi2.bangbang93.com/maven" }
}

dependencies {
    // Only Forge is required; no extra libraries.
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "1.8.9"

    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"
        expand version: project.version, mcversion: "1.8.9"
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}

jar {
    manifest {
        attributes 'FMLCorePlugin': 'com.lindedaoqwq.linclient.core.LinClientCorePlugin',
                   'FMLCorePluginContainsFMLMod': 'true'
    }
}
