modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="linclient"
version="${file.jarVersion}"
displayName="LinClient"
description="Practical client-side HUD, information display and performance/visual optimization. No cheating, no server-side behavior changes."
authors="lindedaoqwq"
credits="Built with ForgeGradle"
logoFile=""
url="https://github.com/lindedaoqwq/Minecraft-LinClient"

[[dependencies.linclient]]
modId="forge"
type="required"
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.linclient]]
modId="minecraft"
type="required"
versionRange="[1.20.1]"
ordering="NONE"
side="CLIENT"
